# Uncomment this line to define a global platform for your project
# platform :ios, ‘8.0’

target 'chrnword' do
	pod 'AFNetworking', '~> 2.5.4'
    pod 'Kiwi', '~> 2.3.1'
	pod 'TesseractOCRiOS', '~> 4.0.0'
	

end



